### ISSUE TITLE
What is the benefit of these lines?

### ISSUE THREAD

**Issue by signorrayan** [hashlookup/hashlookup-json-importer#2]
Could you please tell me what is the benefit of lines 59, 60 and 62?
Is it for future options or I'm wrong.

```
if record[key] == "":
    continue
```

**Comment by adulau** [comment]
It's to avoid the insertion of empty field record. It's quite common to have tools producing empty hashes for fuzzy hashing when the files are small. It's the case for SSDEEP and TLSH.
